language: minimal
dist: trusty
matrix:
  include:
    - language: go
      dist: bionic
      go: "1.12"
      env: GO=go
    - language: go
      dist: bionic
      go: "1.13"
      env: GO=go
    - language: go
      dist: bionic
      go: "1.14"
      env: GO=go
    - language: go
      dist: bionic
      go: "1.15"
      env: GO=go
before_install:
  # Try to check out a branch of the same name from the snowball-data repo
  # sibling of this snowball repo, so that PRs requiring changes to both can be
  # CI tested easily.
  #
  # If that fails, just use the standard snowball-data repo's default branch.
  - GH_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - GH_REPO_SLUG=${TRAVIS_PULL_REQUEST_SLUG:-$TRAVIS_REPO_SLUG}
  - GH_REPO_URL=https://github.com/${GH_REPO_SLUG%%/*}/snowball-data.git
  - echo "Trying branch $GH_BRANCH from $GH_REPO_URL"
  - git clone --depth=1 -b "$GH_BRANCH" "$GH_REPO_URL" || git clone --depth=1 https://github.com/snowballstem/snowball-data.git
script:
  - make CC="${CC:-gcc}"
  - test -z "$CFLAGS_DIST_BUILD" || { pip install setuptools && make dist && mkdir tmp && cd tmp && tar xf ../dist/libstemmer_c.tgz && cd libstemmer_c && make CFLAGS="$CFLAGS_DIST_BUILD" ; }
  - test -z "$c_tests" || make check CC="${CC:-gcc}" STEMMING_DATA=snowball-data
  - test -z "$PYTHON" || make check_python python="$PYTHON" STEMMING_DATA=snowball-data
  - test -z "$JAVA" -o -z "$JAVAC" || make check_java STEMMING_DATA=snowball-data
  - test -z "$MCS" || make check_csharp MCS="$MCS" STEMMING_DATA=snowball-data
  - test -z "$NODE" || make check_js STEMMING_DATA=snowball-data
  - test -z "$RUST" || make check_rust STEMMING_DATA=snowball-data
  - test -z "$RUST" || make check_rust cargoflags=--release STEMMING_DATA=snowball-data
  - test -z "$GO" || make check_go STEMMING_DATA=snowball-data
  - test -z "$FPC" || make check_pascal STEMMING_DATA=snowball-data
